version: '3'

services:
  redis-card-watcher:
    image: redis:7.0
    ports:
      - "${REDIS_PORT_HOST}:6379"
    networks:
      - scraper

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis-card-watcher
      - selenium
    environment:
      - REDIS_HOST=redis-card-watcher
      - REDIS_PORT=${REDIS_PORT}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - scraper

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - scraper

networks:
  scraper:
